services:
  - type: web
    name: proyecto-final-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    autoDeploy: true