services:
  - type: web
    name: proyecto-final-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/backend-proyectoFinal.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        value: jdbc:postgresql://dpg-d4baveje5dus73ehg0k0-a.internal:5432/bd_outfitfinder
      - key: DATABASE_USERNAME
        value: backend_admin
      - key: DATABASE_PASSWORD
        value: jPcXBKOWl5v1JaxfGN0qmtIvN8isFEXK
    autoDeploy: true