services:
  - type: web
    name: proyecto-final-backend
    runtime: docker
    plan: free
    autoDeploy: true

    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod

      - key: DATABASE_URL
        value: jdbc:postgresql://dpg-d4baveje5dus73ehg0k0-a.internal:5432/bd_outfitfinder

      - key: DATABASE_USERNAME
        value: backend_admin

      - key: DATABASE_PASSWORD
        value: jPcXBKOWl5v1JaxfGN0qmtIvN8isFEXK
